version: "3.3"
services:

  main:
    image: "${DOCKER_IMAGE?Variable not set}:${TAG-latest}"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_DEBUG_PLUGINS=${QT_DEBUG_PLUGINS}
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/yaricp/projects/yaricp/EEG:/data
    command:
      - poetry run python /app/src/main.py
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        INSTALL_TZ: ${INSTALL_TZ}

volumes:
  app-db-data:
