[tool.poetry]
name = "qt5-eeg-filters"
version = "0.2.0"
description = ""
authors = ["Yaroslav Pisarev"]
license = "ISP"

[tool.poetry.dependencies]
python = "^3.12"
eeg-filters = "^0.0.8"
ep-bandpass-filter-selector = "^0.0.5"
pyqt5 = "^5.15.11"
loguru = "^0.7.3"
pandas = "^2.2.3"
numpy = "^2.2.4"
pyqtgraph = "^0.13.7"
pyedflib = "^0.1.40"
scipy = "^1.15.2"
matplotlib = "^3.10.1"

[tool.poetry.dev-dependencies]
flake8 = "^7.3.0"
ruff = "^0.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
