name: Run check format lint, unittests and test publication package
on:
  push:
    branches:
      - dev

jobs:
  run-linters-unittests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          bash -c ./scripts/./local_install.sh;

          ls -a;
      - name: run linters
        run: |
          poetry run flake8 src
          # poetry run ruff check src
      # - name: run unittests
      #   run: .venv/bin/poetry run pytest

  build_publish_ubuntu_image:
    needs: run-linters-unittests
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build a new docker image
        env:
          DOCKER_IMAGE: "ghcr.io/yaricp/qt5-eeg-filters-ubuntu"
          DOCKERFILE: DockerfileUbuntu
          TAG: "test"
        run: docker compose build
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_RUNNER }}
      - name: make tag to latest
        run: |
          docker tag ghcr.io/yaricp/qt5-eeg-filters-ubuntu:test ghcr.io/yaricp/qt5-eeg-filters-ubuntu:latest
      - name: Publish test tag to github
        env:
          DOCKER_IMAGE: "ghcr.io/yaricp/qt5-eeg-filters-ubuntu"
          TAG: "test"
        run: docker compose push
      - name: Publish latest tag to github
        env:
          DOCKER_IMAGE: "ghcr.io/yaricp/qt5-eeg-filters-ubuntu"
          TAG: "latest"
        run: docker compose push
      # - name: Publish to dockerhub
      #   env:
      #     DOCKER_IMAGE: "yaricp/qt5-eeg-filters-ubuntu"
      #     TAG: "test"
      #   run: |
      #     docker login -u yaricp
      #     docker compose push
