name: Run check format lint, unittests and test publication package
on:
  push:
    branches:
      - dev

jobs:
  run-linters-unittests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          bash -c ./scripts/./local_install.sh;
          
          ls -a;
      - name: run linters
        run: |
          poetry run flake8 eeg_filters
          poetry run ruff check eeg_filters
      # - name: run unittests
      #   run: .venv/bin/poetry run pytest

  test_build_public_package:
    needs: run-linters-unittests
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Build a new docker image
        env:
          DOCKER_IMAGE: "ghcr.io/yaricp/qt5-eeg-filters"
          TAG: "test"
        run: docker-compose build
      - name: Publish to github
        run: docker-compose push
      - name: Publish to github
        env:
          DOCKER_IMAGE: "yaricp/qt5-eeg-filters"
          TAG: "test"
        run: |
          docker login -u yaricp
          docker-compose push
